### ISSUE TITLE
Lots of skipped tests on Travis

### ISSUE THREAD

**Issue by michalbundyra** [zendframework/zend-session#100]
Currently we have a lot of skipped test on Travis build:

```
...............................................................  63 / 660 (  9%)
...SSSS..SSSSSS......................SSSSSSSSSSSSSSSSSSSSSSSSSS 126 / 660 ( 19%)
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS 189 / 660 ( 28%)
SSSSSSSSSSSSSSSSS..SSSSSSSS.................................... 252 / 660 ( 38%)
...S...I....................................................... 315 / 660 ( 47%)
.....SS..SSSS..........SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS 378 / 660 ( 57%)
SSSSSSSSSSSS..SSSS..................................S.......... 441 / 660 ( 66%)
............................................................... 504 / 660 ( 76%)
............................................................... 567 / 660 ( 85%)
....................S.....SS.........SSSS...................... 630 / 660 ( 95%)
..............................                                  660 / 660 (100%)
```

Would be nice to update configuration to enable these tests.

**Comment by thexpand** [comment]
@webimpress 
Most of the tests are skipped, because of `session.*` configuration directives, removed in PHP 7.1 (e.g. `session.entropy_file`, `session.entropy_length`, `session.hash_function`). As we still provide support for `"php": "^5.6 || ^7.0"`, as far as I know there is nothing that we can do about it.

Other tests are being skipped, because they require the PDO_Sqlite extension.

**Comment by michalbundyra** [comment]
@thexpand thanks for checking it, I had another look and you are right, many tests are skipped because of PHP version constraint - some runs on PHP 7.1+ others on previous versions only.
